language: node_js
node_js:
- stable
sudo: false
cache:
  directories:
  - node_modules
  - jspm_packages
branches:
  only:
  - master
before_install:
- npm i -g jspm
- npm i -g typings
- jspm config registries.github.auth "$JSPM_GITHUB_AUTH_TOKEN"
install:
- npm i
- typings i
- jspm i
script:
- gulp build
- gulp test
notifications:
 webhooks:
  urls:
    - https://webhooks.gitter.im/e/57bb56e739e8810e31c6
  on_success: always
  on_failure: always
  on_start: never
after_success:
  - bash <(curl -s https://codecov.io/bash)